### ISSUE TITLE
environment question

### ISSUE THREAD

**Issue by bao666liang** [JM-Kim-94/rl-mobile-robot-SAC#1]
[ INFO] [1650269147.989569531, 34523.438000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1650269147.999950504, 34523.524000000]: Physics dynamic reconfigure ready.
DEVICE :  cuda
[spawn_urdf-3] process has finished cleanly
log file: /home/wanbaoliang/.ros/log/13227772-beed-11ec-8a00-63681b92ee34/spawn_urdf-3*.log
ACTOR:
 PolicyNet_1225(
  (fc_1): Linear(in_features=4, out_features=128, bias=True)
  (fc_2): Linear(in_features=128, out_features=128, bias=True)
  (fc_3): Linear(in_features=128, out_features=64, bias=True)
  (fc_mu): Linear(in_features=64, out_features=2, bias=True)
  (fc_std): Linear(in_features=64, out_features=2, bias=True)
)

The program doesn't run here and the gazebo model doesn't move. What's the reason?
version: noetic  gazebo11 ptyorch10.0

**Comment by JM-Kim-94** [comment]
Thank you for interests in my project

Which launch file did you use?

This command, 
`& roslaunch myrobot mobile_robot_SAC.launch`
might work. 

The Gazebo world maybe need some times to be run depending on your computer performance. 

Actually this project need some update, such as delete unnecessary code, requirements list, and how to use. 
I will update this repository as soon as possible.
